# CONFIGURACIÓN DEL SISTEMA DE INCIDENCIAS

# Entorno y red
entorno=desarrollo
servidor.puerto=8080

# Rutas del sistema
rutas.exportacion=./exportaciones
rutas.logs=./logs

# Comportamiento
app.modo_depuracion=true

# Valores por defecto del negocio
defecto.incidencia.prioridad=3
defecto.incidencia.estado=ABIERTA