# CONFIGURACIÓN DEL SISTEMA DE INCIDENCIAS

# Entorno y red
entorno=desarrollo
servidor.puerto=8080

# Rutas del sistema
rutas.exportacion=./exportaciones
rutas.logs=./logs

# Comportamiento
app.modo_depuracion=true

# Valores por defecto del negocio
defecto.incidencia.prioridad=3
defecto.incidencia.estado=ABIERTA

# Base de Datos
db.url=jdbc:mysql://localhost:3306/proyecto_incidencias?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=PONER_PASSWORD_AQUI